// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/navbar/Navbar';
import LoginModal from "./components/models/LoginModel";
import SignupModal from "./components/models/signupmodel";
import Footer from "./components/footer/footer";
import { Providers } from "./redux/providers/providers";
import SearchModal from "./components/models/SearchModel";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "HomeSphere",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          <Navbar />
          <div className="pt-32">
            {children}
          </div >
          <SearchModal />
          <LoginModal />
          <SignupModal />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
