
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/navbar/Navbar';
import LoginModal from "./components/models/LoginModel";
import SignupModal from "./components/models/signupmodel";
import Footer from "./components/footer/footer";
import { Providers } from "./redux/providers/providers";
import SearchModal from "./components/models/SearchModel";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HomeSphere",
  description: "Generated by Ishita",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Providers>
          <Navbar />
          <ToastContainer />
          <div className="pt-32">
            {children}
          </div >
          <SearchModal />
          <LoginModal />
          <SignupModal />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
